### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by poguez** [hefan/spree_dynamic_variants#1]
I am using spree 3-0-stable

<img width="522" alt="screen shot 2016-09-19 at 10 00 27 am" src="https://cloud.githubusercontent.com/assets/732015/18620561/fe61ad64-7e4f-11e6-87b3-28dfd8a2f19d.png">

**Comment by poguez** [comment]
Sorry, I checked out at the wrong version in my Gemfile.

**Comment by hefan** [comment]
i like to hear that somebody uses it :). Hope it's helpful.
