### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by TheSmokingDev** [hefan/spree_dynamic_variants#2]
Hey, just wanted to know if you plan on updating this at some point?
it looks really useful!
cheers

**Comment by s3749653** [comment]
All good, got it too work with the new API. This extension is absolutely beautiful. Thank you!

**Comment by hefan** [comment]
Thank you. Nice to know it is used. i abandoned it a little bit for the solidus version of the gem. But i will have a look into it and bump it to be compatible to the latest spree releases these days!

**Comment by hefan** [comment]
For now it only works up to version 3.7
